### ISSUE TITLE
Not able to open issues on openwashdata/wasteskipsblantyre repo

### ISSUE THREAD

**Issue by sebastian-loos** [Global-Health-Engineering/data-public-waste-skips-blantyre#1]
Hey @larnsce, @mianzg and @mbannert 

I'm almost ready to publish the Blantyre waste skips data set into as an openwashdate data package.

For the final touches, I wanted to collaborate with Mabvuto and open some issues. Unfortunately, I'm not able to create any issues in the [openwashdata/wasteskipsblantyre](https://github.com/openwashdata/wasteskipsblantyre) repo. I don't know how I messed it up and when, but on github I don't have the option of creating an issue anywhere on this repo. 

Also the issue tab doesn't show up.
![image](https://github.com/Global-Health-Engineering/data-public-waste-skips-blantyre/assets/100614166/4ecd7659-7155-4db1-940e-b768a8a2690e)

Nevertheless, I can create issues in the [GHE repo](https://github.com/Global-Health-Engineering/data-public-waste-skips-blantyre).
I actually don't need to solve this problem since I should be able to work around (Mabvuto is in the office). I'm just wondering what happened or if I did anything wrong. Anybody has some advice?

Additionally, the branches are always compared with the GHE:main branch (therefore, main is 19 commits ahead and 2 commits behind). Is there a way to change that?

Thanks for your time!

**Comment by mianzg** [comment]
I added the Issues in the forked repository according to : https://stackoverflow.com/questions/16406180/is-there-a-way-to-add-issues-to-a-github-forked-repo-without-modifying-the-orig

**Comment by mianzg** [comment]
> Additionally, the branches are always compared with the GHE:main branch (therefore, main is 19 commits ahead and 2 commits behind). Is there a way to change that?

I didn't find anything about this. I don't think so because it is then against the philosophy of Forking. Maybe the display is changed if the original repository is archived.

**Comment by larnsce** [comment]
@sebastian-loos: is the problem about not being able to open an issue sorted?

> Additionally, the branches are always compared with the GHE:main branch (therefore, main is 19 commits ahead and 2 commits behind). Is there a way to change that?

No, that can't be changed. But, when you open a PR you can change against which main branch the PR is opened, so that it does not do it against the forked repository. 

<img width="1022" alt="Screenshot 2023-07-24 at 15 20 05" src="https://github.com/Global-Health-Engineering/data-public-waste-skips-blantyre/assets/18212549/36a66c7c-773f-4ef2-b9c3-c28271b2669c">

**Comment by sebastian-loos** [comment]
> @sebastian-loos: is the problem about not being able to open an issue sorted?

It is solved, thanks @Mian!!

> No, that can't be changed. But, when you open a PR you can change against which main branch the PR is opened, so that it does not do it against the forked repository.

Okey, it's actually not an issue. It just catches my every time I open the repo. It's kind of  the same stimulation to when I see that I have unread messages and immediately want to check it 😄 Thanks for checking.

I'll go ahead and close this Issue...
